### ISSUE TITLE
Failed setup, will retry: Error communicating with API: TimeoutError()n - Home assistant 2025.1.0

### ISSUE THREAD

**Issue by Coastersteve** [ofalvai/home-assistant-candy#302]
My Candy plug add on hasn’t been able to connect to the Candy API for a week or so now.

**Comment by byte4geek** [comment]
Hi all,
same issue.
From the logs:
```
2025-01-10 13:45:25.338 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Candy for candy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/candy/__init__.py", line 54, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(config_entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2278, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1185, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1173, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1098, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1272, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1304, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/candy/sensor.py", line 6, in <module>
    from homeassistant.const import TEMP_CELSIUS, TIME_MINUTES
ImportError: cannot import name 'TEMP_CELSIUS' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
```

**Comment by byte4geek** [comment]
i fixed it by replacing sensor.py using this file:
https://github.com/ofalvai/home-assistant-candy/blob/8f2f6dd248ebae1cd756851e7430ea40a96fea20/custom_components/candy/sensor.py

**Comment by Coastersteve** [comment]
> i fixed it by replacing sensor.py using this file: https://github.com/ofalvai/home-assistant-candy/blob/8f2f6dd248ebae1cd756851e7430ea40a96fea20/custom_components/candy/sensor.py

Thanks for the repy. I've just tried and it hasn't made any difference to mine :-(

**Comment by MacSiem** [comment]
I have the same issue and replacing sensor.py did not fix it in My case.

**Comment by xlibbyx** [comment]
This seems to be a problem again?
